[cite_start]name: CI  # Назва пайплайну [cite: 29]

on:
  push:
    [cite_start]branches: [ main ] # Запуск при завантаженні коду [cite: 30]
  pull_request:
    [cite_start]branches: [ main ] # Запуск при створенні PR [cite: 30]

jobs:
  build-and-test:
    [cite_start]runs-on: ubuntu-latest # Використовуємо Linux [cite: 31]

    steps:
      - name: Checkout code
        [cite_start]uses: actions/checkout@v4 # Копіюємо код [cite: 33]

      - name: Install dependencies
        [cite_start]run: npm install # Встановлення (якщо у тебе Node.js) [cite: 36]

      - name: Run tests
        [cite_start]run: npm test # Запуск тестів [cite: 39]
