name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Встановити Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Встановити залежності
        run: npm install

      - name: Збірка
        run: npm run build
        continue-on-error: true

      - name: Тести
        run: npm test
        continue-on-error: true
